<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxob0qt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxob0qt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYxob0qt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYxob0qt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYxob0qt\appProdProjectContainer([
    'container.build_hash' => 'Yxob0qt',
    'container.build_id' => '1e3e4695',
    'container.build_time' => 1632145351,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxob0qt');
